# Generated by Django 4.2.11 on 2025-09-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="agent_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
