# Generated by Django 5.2.6 on 2025-09-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_agent_agent_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('tool_id', models.AutoField(help_text='Unique ID for each tool.', primary_key=True, serialize=False)),
                ('tool_name', models.CharField(help_text='The name of the tool.', max_length=255, unique=True)),
                ('tool_description', models.TextField(help_text='A description of what the tool does.')),
                ('meta_data', models.JSONField(help_text='A JSON object that defines the required parameters for the tool.')),
            ],
        ),
    ]
