# Generated by Django 5.2.4 on 2025-09-08 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
        ('runs', '0002_run_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='conversation',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='conversations.conversation'),
        ),
    ]
