# Generated by Django 5.2.6 on 2025-09-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0004_alter_run_conversation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
