# Generated by Django 4.2.24 on 2025-09-08 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_tool"),
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Step",
            fields=[
                ("step_id", models.AutoField(primary_key=True, serialize=False)),
                ("step_order", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("thought", "Thought"),
                            ("tool_call", "Tool Call"),
                            ("observation", "Observation"),
                            ("sub_agent_call", "Sub Agent Call"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="agents.agent",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="agents.tool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Step",
                "verbose_name_plural": "Steps",
                "ordering": ["conversation", "step_order"],
                "indexes": [
                    models.Index(
                        fields=["conversation", "step_order"],
                        name="conversatio_convers_5f7d2d_idx",
                    )
                ],
            },
        ),
    ]
